---
title: "Yuqi_Q2"
author: "Yuqi Miao ym2771"
date: "4/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
# library(lmerTest)
library(xlsx)
library(gtsummary)
library(mice)
library(flexsurv)
library(xtable)
data= readxl::read_excel("Q2b.xlsx")
baseline = readxl::read_excel("Q2b_BL.xlsx")
data_all = left_join(data, baseline, by = "ID") %>% 
  janitor::clean_names() %>% 
  mutate(time = factor(time),
         sex = factor(sex, level = c(0,1),
                      label = c("female","male")),
         group = factor(group, levels = c(0,1),
                        labels = c("control", "vaccine"))
         ) 
data_spread = data_all %>% 
  pivot_wider(names_from = time,
              names_prefix = "time",
              values_from = sae,
              id_cols = id
              )
```

# Q2: 

## Descriptive table

```{r}
table1 = data_all %>% 
  filter(time == 1) %>% 
  select(-time) %>% 
  tbl_summary(by = group) %>% 
  add_p()
```

## Missing pattern

```{r}
data_spread_tmp = data_spread %>% 
  dplyr::select(time1, time2, time3)
md_pattern = md.pattern(data_spread_tmp,plot = T)

save(md_pattern, file = "md_pattern.Rdata")
```


* Assume missing at random?

Use LR to verify not missing completely at random
* Simply separating missing and non-missing as 2 pattern
# 0 for complete, 1 for missing
```{r}
missing_id = apply(data_spread, 1, function(x){
  if(sum(is.na(x)) == 0){
    return(0)
  }else{
    return(1)
  }
})

data_spread = data_spread %>% mutate(missing_id = missing_id)
data_all_mis = data_all %>% 
  left_join(data_spread %>% select(id,missing_id), by = "id")

summary(lm(missing_id~group, data = data_all_mis)) 
# also easy to observe from table1, more missing in trt group

summary(lm(missing_id~sae,data = data_all_mis)) 
# Not related to outcome, MAR may hold

summary(lm(missing_id~sex,data = data_all_mis)) 
summary(lm(missing_id~age, data = data_all_mis)) 
# lower age tend to missing more
summary(lm(missing_id~site,data = data_all_mis))
```

GLM for missing pattern
```{r}
missing_glm = glm(missing_id~sae+sex+age+site+time, 
                  data = data_all_mis,
                  family=binomial(link='logit'),
                  na.action = na.omit)

summary(missing_glm)
save(missing_glm, file = "missing_glm.Rdata")
texreg::texreg(missing_glm, caption = "missing_id~sae+sex+age+site")

xtable(missing_glm)
```

## Data visualization

```{r}
data_all %>% 
  mutate(age_group = cut(age,3)) %>% 
  group_by(sex, age_group, group, time) %>% 
  summarize(mean_sae = mean(sae, na.rm = T)) %>% 
  ggplot(aes(x = time, y = mean_sae, fill = group))+
  geom_bar(stat = "identity", position = "dodge")+
  facet_grid(sex~age_group)

data_all %>% 
  mutate(age_group = cut(age,3)) %>% 
  group_by(age, group) %>% 
  summarize(mean_sae = mean(sae, na.rm = T)) %>% 
  ggplot(aes(x = age, y = mean_sae, fill = group))+
  geom_bar(stat = "identity", position = "dodge")
```


## GLM for prior fitting

```{r}
# fit1 = glmer(sae~time:group+time+sex+age+(1|site/id), data = data_all,family = binomial, na.action = na.omit)
# save(fit1, file = "fit1.Rdata")
# summary(fit1)
# anova(fit1)
```

```{r}
# fit1 = glmer(sae~time:group+time+sex+age+(1|site/group), data = data_all,family = binomial, na.action = na.omit)
# save(fit1, file = "fit1.Rdata")
# summary(fit1)
# anova(fit1)
```


```{r}
fit1 = glm(sae~time:group+time+sex+age,
           data = data_all,
           family=binomial(link='logit'),
           na.action = na.omit)
summary(fit1)
```

## [result] using glmmTMB
```{r}
library(glmmTMB)
# fit1 = glmmTMB(sae~time:group+time+sex+age+(1|site/id), data = data_all,family = binomial, na.action = na.omit)
# # save(fit1, file = "fit1.Rdata")
# # load("fit1.Rdata")
# # fixef(fit1)
# summary(fit1)
```

```{r}
fit2 = glmmTMB(sae~time:group+time+sex+age+(1|site/group), 
               data = data_all,
               family = binomial, na.action = na.omit)
summary(fit2)
save(fit2, file = "fit2.Rdata")
```

### Anova

### Output plot and table

```{r}
ss <- summary(fit2)
## print table; add space,
pxt <- function(x,title) {
  cat(sprintf("{\n\n\\textbf{%s}\n\\ \\\\\\vspace{2pt}\\ \\\\\n",title))
  print(xtable(x), floating=FALSE); cat("\n\n")
  cat("\\ \\\\\\vspace{5pt}\\ \\\\\n")
}

pxt(coef(ss)$cond,"conditional fixed effects")
```


## PMM

```{r}
fit_pmm = data_all_mis %>% 
  nest(data = -missing_id) %>% 
  arrange(missing_id = desc(missing_id)) %>% 
  mutate(fit = map(data, function(data){
    fit1 = glmmTMB(sae~time:group+time+sex+age+(1|site/id),
                   data = data,family = binomial, na.action = na.omit)
    fit1
  }))
  
mod_list = list(mod_mis1 = fit_pmm$fit[[1]],
                mod_mis0 = fit_pmm$fit[[2]],
                mod_all = fit1)

save(mod_list, file = "mod_list.Rdata")

load("mod_list.Rdata")
summary(mod_list$mod_mis1)
summary(mod_list$mod_mis0)
summary(mod_list$mod_all)
texreg::texreg(mod_list)
```




```{r}
fit_pmm = data_all_mis %>% 
  nest(data = -missing_id) %>% 
  arrange(missing_id = desc(missing_id)) %>% 
  mutate(fit = map(data, function(data){
    fit1 = glmer(sae~time:group+time+sex+age+(1|site/id),
                 data = data,family = binomial, na.action = na.omit)
    fit1
  }))

fit_all = lme4::glmer(sae~time:group+time+sex+age+(1|site/id), 
                data = data_all,family = binomial, na.action = na.omit)

mod_list = list(mod_mis1 = fit_pmm$fit[[1]],
                mod_mis0 = fit_pmm$fit[[2]],
                mod_all = fit1)

summary(mod_list$mod_mis1)
summary(mod_list$mod_mis0)
summary(mod_list$mod_all)
```





```{r}
p2 = 0.04
rho = 0.005
lambda = 0.01
z_a = qnorm(0.05,0,1)
z_b = qnorm(0.2,0,1)
R1 = 0.4
R0 = 0.7
q2 = 1-p2
p1 = p2*R1
q1 = 1-p1
p1_0 = p2*R0
q1_0 = 1-p1_0
k = 1/2

# Likelihood score -- mietten ?
N1 = (z_a*sqrt(p1_0*q1_0/k+R0^2*p2*q2/(1-k))+
  z_b*sqrt(p1*q1/k+R0^2*p2*q2/(1-k)))^2/(R0*p2-p1)^2
N1 # Not 2120

# logarithmic
N2=((z_a+z_b)^2*(q1/(k*p1)+q2/((1-k)*p2)))/(log(R0)-log(R1))^2
N2 = N2*(1+(50-1)*rho)*(1/(1-lambda))
N2
```

#Q1:  Sample size table 

```{r}
sens_samp_tib = expand_grid(p2 = c(0.01,0.03,0.05),
            rho = c(0,0.005,0.01),
            lambda = c(0,0.005,0.01)) %>% 
  mutate(n = pmap_dbl(list(p2 = p2, rho = rho, lambda = lambda),
                      function(p2, rho, lambda){
                        z_a = qnorm(0.05,0,1)
                        z_b = qnorm(0.2,0,1)
                        R1 = 0.4
                        R0 = 0.7
                        q2 = 1-p2
                        p1 = p2*R1
                        q1 = 1-p1
                        p1_0 = p2*R0
                        q1_0 = 1-p1_0
                        k = 1/2
                        
                        # Likelihood score -- mietten ?
                        N1 = (z_a*sqrt(p1_0*q1_0/k+R0^2*p2*q2/(1-k))+
                          z_b*sqrt(p1*q1/k+R0^2*p2*q2/(1-k)))^2/(R0*p2-p1)^2
                        N1 # Not 2120
                        
                        # logarithmic
                        N2=((z_a+z_b)^2*(q1/(k*p1)+q2/((1-k)*p2)))/(log(R0)-log(R1))^2
                        N2 = N2*(1+(50-1)*rho)*(1/(1-lambda))
                        N2
                      }))

save(sens_samp_tib, file = "sens_samp_tib.Rdata")
```

# Survival

```{r}
surv_data = readxl::read_excel("Q2c.xlsx") %>% 
  janitor::clean_names()
```


```{r}
# model----
exp1 <- flexsurvreg(Surv(last_fu_time, infection) ~ 1,
                    data = surv_data,
                    dist = "exp")  # S(t)=e^{-rate*t} 
plot(exp1, xlab = "Last FU time", ylab = "survival probability",
    main = "KM and exponential estimates of survival curve")
# median menopause time ----
## summary(exp1) #get the estimate and ci tab
summary(exp1, type = "quantile", quantiles = 0.5)
exp_med_sum = round(summary(exp1, type = "quantile", quantiles = 0.5)[[1]],2)
exp_med_ci = paste(exp_med_sum[2], "(", exp_med_sum[3], ",", exp_med_sum[4],")", sep = "")
```

```{r}
KM1=survfit(Surv(last_fu_time, infection)~1, data = surv_data, conf.type='log')
plot(KM1, conf.int = T, mark.time = TRUE,xlab="Last fu time", ylab="survival probability", main="K-M curve", cex.lab=1.5, cex.main=1.5)
# obtain survival rate at given time, with CI
summary(KM1) 
# median survival time, with CI
print(KM1)
```


```{r}
# mode2----
exp1 <- flexsurvreg(Surv(last_fu_time, infection) ~ 1,
                    data = surv_data,
                    dist = "exp")  # S(t)=e^{-rate*t} 
plot(exp1, xlab = "Last FU time", ylab = "survival probability",
    main = "KM and exponential estimates of survival curve")
# median menopause time ----
## summary(exp1) #get the estimate and ci tab
summary(exp1, type = "quantile", quantiles = 0.5)
exp_med_sum = round(summary(exp1, type = "quantile", quantiles = 0.5)[[1]],2)
exp_med_ci = paste(exp_med_sum[2], "(", exp_med_sum[3], ",", exp_med_sum[4],")", sep = "")
```

```{r}
# mode2----
weib1 <- flexsurvreg(Surv(enrollment_time,last_fu_time, infection) ~ 1,
                    data = surv_data,
                    dist = "weibull")  # S(t)=e^{-rate*t} 
plot(weib1, xlab = "Last FU time", ylab = "survival probability",
    main = "KM and weib estimates of survival curve")
# median menopause time ----
## summary(exp1) #get the estimate and ci tab
summary(weib1, type = "quantile", quantiles = 0.5)
weib_med_sum = round(summary(weib1, type = "quantile", quantiles = 0.5)[[1]],2)
weib_med_ci = paste(weib_med_sum[2], "(", weib_med_sum[3], ",", weib_med_sum[4],")", sep = "")
```

```{r}
KM1=survfit(Surv(last_fu_time, infection)~1, data = surv_data, conf.type='log')
plot(KM1, conf.int = T, mark.time = TRUE,xlab="Last fu time", ylab="survival probability", main="K-M curve", cex.lab=1.5, cex.main=1.5)
# obtain survival rate at given time, with CI
summary(KM1) 
# median survival time, with CI
print(KM1)
```




